# Generated by Django 2.0.4 on 2018-05-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_album', models.CharField(max_length=100, verbose_name="Nom de l'album")),
                ('numero_piste', models.IntegerField(verbose_name='Numéro de la piste')),
                ('titre', models.CharField(max_length=100)),
                ('autheur', models.CharField(max_length=100, null=True)),
                ('compositeur', models.CharField(max_length=100, null=True)),
                ('interprete', models.CharField(max_length=100)),
                ('url_pochette', models.URLField(verbose_name='Url de la pochette')),
            ],
            options={
                'verbose_name': 'music',
                'ordering': ['nom_album'],
            },
        ),
    ]
